service: multi-bin
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  architecture: arm64

plugins:
  - serverless-rust-plugin

custom:
  rust:
    cargoLambda:
      docker: false

functions:
  useFirstName:
    name: useFirstName
    handler: multi-binary.first

  useLastName:
    name: useLastName
    handler: multi-binary.last
